const animalResponses = [
  {
    name: "Cross River Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla gorilla diehli",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Fruit, Flowers",
      habitat: "Rainforest and dense jungle",
      predators: "Human, Leopard, Crocodile",
      diet: "Herbivore",
      average_litter_size: "1",
      lifestyle: "Troop",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "Less than 300 remaining!",
      color: "GreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35 - 50 years",
      weight: "100kg - 200kg (220lbs - 440lbs)",
      height: "1.4m - 1.7m (4.7ft - 5.5ft)",
    },
  },
  {
    name: "Eastern Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla berengei",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Seeds, Herbs",
      habitat: "Tropical forest and jungles in mountainous regions",
      predators: "Human, Leopard",
      diet: "Omnivore",
      average_litter_size: "1",
      lifestyle: "Social",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "The largest primate in the world!",
      color: "BrownGreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35 - 50 years",
      weight: "204kg - 227kg (450lbs - 500lbs)",
      height: "1.5m - 1.8m (5ft - 6ft)",
    },
  },
  {
    name: "Eastern Lowland Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla Berengei Graueri",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Seeds, Herbs",
      habitat: "Tropical forest and jungles in mountainous regions",
      predators: "Human, Leopard",
      diet: "Omnivore",
      average_litter_size: "1",
      lifestyle: "Social",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "Less than 5,000 in the wild!",
      color: "BrownGreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35 - 50 years",
      weight: "204kg - 227kg (450lbs - 500lbs)",
      height: "1.5m - 1.8m (5ft - 6ft)",
    },
  },
  {
    name: "Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Fruit, Flowers",
      habitat: "Rainforest and dense jungle",
      predators: "Human, Leopard, Crocodile",
      diet: "Omnivore",
      average_litter_size: "1",
      lifestyle: "Troop",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "The biggest of the world's primates!",
      color: "GreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35-50 years",
      weight: "100-200kg (220-440lbs)",
    },
  },
  {
    name: "Mountain Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla Berengei Berengei",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Seeds, Herbs",
      habitat: "Tropical forest and jungles in mountainous regions",
      predators: "Human, Leopard",
      diet: "Omnivore",
      average_litter_size: "1",
      lifestyle: "Social",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "Isolated populations found in the mountains!",
      color: "BrownGreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35-50 years",
      weight: "204-227kg (450-500lbs)",
    },
  },
  {
    name: "Western Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla Gorilla",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Fruit, Flowers",
      habitat: "Rainforest and dense jungle",
      predators: "Human, Leopard, Crocodile",
      diet: "Herbivore",
      average_litter_size: "1",
      lifestyle: "Troop",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "There are two sub-species!",
      color: "GreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35 - 50 years",
      weight: "100kg - 200kg (220lbs - 440lbs)",
      height: "1.4m - 1.7m (4.7ft - 5.5ft)",
    },
  },
  {
    name: "Western Lowland Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla gorilla gorilla",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Fruit, Flowers",
      habitat: "Rainforest and dense jungle",
      predators: "Human, Leopard, Crocodile",
      diet: "Herbivore",
      average_litter_size: "1",
      lifestyle: "Troop",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "One of the great apes!",
      color: "GreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35 - 50 years",
      weight: "100kg - 200kg (220lbs - 440lbs)",
      height: "1.4m - 1.7m (4.7ft - 5.5ft)",
    },
  },
];

module.exports = { animalResponses };
