[
  {
    name: "Cross River Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla gorilla diehli",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Fruit, Flowers",
      habitat: "Rainforest and dense jungle",
      predators: "Human, Leopard, Crocodile",
      diet: "Herbivore",
      average_litter_size: "1",
      lifestyle: "Troop",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "Less than 300 remaining!",
      color: "GreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35 - 50 years",
      weight: "100kg - 200kg (220lbs - 440lbs)",
      height: "1.4m - 1.7m (4.7ft - 5.5ft)",
    },
    photoData: [
      {
        animalName: "Cross River Gorilla",
        image:
          "http://farm66.static.flickr.com/65535/52427315695_17836d4560.jpg",
        url: "http://www.flickr.com/photos/36612849@N08/52427315695",
        title: "Cross River Gorilla - Critically Endangered",
      },
    ],
  },
  {
    name: "Eastern Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla berengei",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Seeds, Herbs",
      habitat: "Tropical forest and jungles in mountainous regions",
      predators: "Human, Leopard",
      diet: "Omnivore",
      average_litter_size: "1",
      lifestyle: "Social",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "The largest primate in the world!",
      color: "BrownGreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35 - 50 years",
      weight: "204kg - 227kg (450lbs - 500lbs)",
      height: "1.5m - 1.8m (5ft - 6ft)",
    },
    photoData: [
      {
        animalName: "Eastern Gorilla",
        image: "http://farm5.static.flickr.com/4373/36090382920_cf1264666c.jpg",
        url: "http://www.flickr.com/photos/128578170@N06/36090382920",
        title: "Eastern Gorilla Gorilla beringei",
      },
    ],
  },
  {
    name: "Eastern Lowland Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla Berengei Graueri",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Seeds, Herbs",
      habitat: "Tropical forest and jungles in mountainous regions",
      predators: "Human, Leopard",
      diet: "Omnivore",
      average_litter_size: "1",
      lifestyle: "Social",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "Less than 5,000 in the wild!",
      color: "BrownGreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35 - 50 years",
      weight: "204kg - 227kg (450lbs - 500lbs)",
      height: "1.5m - 1.8m (5ft - 6ft)",
    },
    photoData: [
      {
        animalName: "Eastern Lowland Gorilla",
        image:
          "http://farm66.static.flickr.com/65535/53702867765_716667575b.jpg",
        url: "http://www.flickr.com/photos/62950692@N03/53702867765",
        title: "eastern lowland gorilla amahoro antwerpen 3L0A3179",
      },
    ],
  },
  {
    name: "Mountain Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla Berengei Berengei",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Seeds, Herbs",
      habitat: "Tropical forest and jungles in mountainous regions",
      predators: "Human, Leopard",
      diet: "Omnivore",
      average_litter_size: "1",
      lifestyle: "Social",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "Isolated populations found in the mountains!",
      color: "BrownGreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35-50 years",
      weight: "204-227kg (450-500lbs)",
    },
    photoData: [
      {
        animalName: "Mountain Gorilla",
        image:
          "http://farm66.static.flickr.com/65535/50553992531_7af9e1880d.jpg",
        url: "http://www.flickr.com/photos/58519338@N08/50553992531",
        title: "Mountain Gorillas - Gorilla beringei beringei",
      },
    ],
  },
  {
    name: "Western Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla Gorilla",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Fruit, Flowers",
      habitat: "Rainforest and dense jungle",
      predators: "Human, Leopard, Crocodile",
      diet: "Herbivore",
      average_litter_size: "1",
      lifestyle: "Troop",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "There are two sub-species!",
      color: "GreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35 - 50 years",
      weight: "100kg - 200kg (220lbs - 440lbs)",
      height: "1.4m - 1.7m (4.7ft - 5.5ft)",
    },
    photoData: [
      {
        animalName: "Western Gorilla",
        image: "http://farm9.static.flickr.com/8062/28496468884_e9c642d46a.jpg",
        url: "http://www.flickr.com/photos/26239143@N06/28496468884",
        title: "Western Lowland Gorilla.jpg",
      },
    ],
  },
  {
    name: "Western Lowland Gorilla",
    taxonomy: {
      kingdom: "Animalia",
      phylum: "Chordata",
      class: "Mammalia",
      order: "Primates",
      family: "Hominidae",
      genus: "Gorilla",
      scientific_name: "Gorilla gorilla gorilla",
    },
    locations: ["Africa"],
    characteristics: {
      main_prey: "Leaves, Fruit, Flowers",
      habitat: "Rainforest and dense jungle",
      predators: "Human, Leopard, Crocodile",
      diet: "Herbivore",
      average_litter_size: "1",
      lifestyle: "Troop",
      favorite_food: "Leaves",
      type: "Mammal",
      slogan: "One of the great apes!",
      color: "GreyBlack",
      skin_type: "Hair",
      top_speed: "25 mph",
      lifespan: "35 - 50 years",
      weight: "100kg - 200kg (220lbs - 440lbs)",
      height: "1.4m - 1.7m (4.7ft - 5.5ft)",
    },
    photoData: [
      {
        animalName: "Western Lowland Gorilla",
        image:
          "http://farm66.static.flickr.com/65535/54176722383_5772ce8a30.jpg",
        url: "http://www.flickr.com/photos/136445189@N07/54176722383",
        title: "Western lowland gorilla baby - Apenheul",
      },
    ],
  },
];
